-- Legacy single-lane test builder is intentionally disabled.
-- The playable 6-player map is generated by MapBootstrap.server.lua.

print("[BrainrotFruits] Legacy test lane disabled; BrainrotMap handles the playable layout.")
